# Generated by Django 3.2.19 on 2023-06-01 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20230531_0754'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Content',
            new_name='Contact',
        ),
    ]
