# Generated by Django 3.2.19 on 2023-06-06 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_content_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['created_date']},
        ),
    ]
